version: '3.1'
services:
  php-fpm:
    build: deployment/php-fpm
    working_dir: /app
    volumes:
      - '.:/app'
      - './deployment/php-fpm/php-ini-overrides.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini'
